### PR TITLE
use provided instead of compile, so at apk, there is no nothing about anno-lib

### PR DESCRIPTION
**Pull request by yunair**
anno-lib no need for compile into project, because at annotation processor, it will generate Application Class

### CODE REVIEW

**Comment by shwenzhang** [comment]
please merge the newly dev branch first

**Comment by yunair** [comment]
ok, I has merged newly dev branch

**Comment by shwenzhang** [comment]
pr again？

**Comment by yunair** [comment]
yes, because I commit another file, but dose not mention in this pr

**Pull request closed without merging**
