### PR TITLE
[enhancement] add function that specifies the output folder for tinker patch result.

### PR DESCRIPTION
**Pull request by iluhcm**

### CODE REVIEW

**Comment by shwenzhang** [comment]
will merge with 1.8.0

**Comment by iluhcm** [comment]
I have no permission to edit the wiki, so I follow the instruction on [stackoverflow](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) to create a new [wiki repo](https://github.com/iluhcm/tinker-wiki), how could I make a PR for the wiki documentation?

**Comment by shwenzhang** [comment]
what do you want to edit?

**Comment by iluhcm** [comment]
Just add the instruction of outputFolder, see [here](https://github.com/iluhcm/tinker-wiki/commit/0a4b6a22db8078d639f02be916132e066c9aa489).

**Comment by shwenzhang** [comment]
I want to add the newApk param also

**Comment by iluhcm** [comment]
I'll finish the job later.

**Comment by shwenzhang** [comment]
merged

**Comment by shwenzhang** [comment]
I  move outputFolder and newApk to tinkerPatch closures

**Comment by iluhcm** [comment]
Up to you~

**Pull request merged**
